import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/banner.component.jsx";
import Card from "../components/card/card.component.jsx";
import SectionCards from "../components/card/section-cards.component.jsx";
import Navbar from "../components/nav/navbar.component.jsx";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="ankita@gmail.com" />
      <Banner
        title="Clify"
        subTitle="Very subtitle"
        imgUrl="/static/clifford.webp"
      />
      <SectionCards title="Disney" />
      <Card imgUrl="/static/clifford.webp" size="large" />
      <Card imgUrl="/static/clifford.webp" size="medium" />
      <Card imgUrl="/static/clifford.webp" size="small" />
    </div>
  );
}
