import Head from "next/head";
import Banner from "../components/banner/banner.component.jsx";
import SectionCards from "../components/card/section-cards.component.jsx";
import Navbar from "../components/nav/navbar.component.jsx";
import { getVideos, getPopularVideos } from "../lib/videos.js";
import styles from "../styles/Home.module.css";

export default function Home(initialProps) {
  const { disneyVideos, travelVideos, productivityVideos, popularVideos } =
    initialProps;

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar  />
        <Banner
          title="Clify"
          subTitle="Very subtitle"
          imgUrl="/static/clifford.webp"
          videoId="4zH5iYM4wJo"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards size="large" title="Disney" videos={disneyVideos} />
          <SectionCards size="small" title="Travel" videos={travelVideos} />
          <SectionCards
            size="medium"
            title="Productivity"
            videos={productivityVideos}
          />
          <SectionCards size="small" title="Popular" videos={popularVideos} />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  // get videos on server side and pass it as props to page
  const disneyVideos = await getVideos("disney");
  const travelVideos = await getVideos("Productivity");
  const productivityVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();

  return {
    props: {
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
    },
  };
}
